<!-- Auto-generated by f2c (figma-to-code) | https://github.com/f2c-cli -->
<template>
  <button
    class="inline-flex flex-col items-center justify-center gap-2 rounded-full px-4 hover:opacity-85 active:opacity-70 cursor-pointer"
    :style="{ backgroundColor: 'rgb(13,13,13)' }"
  >
    <div class="flex flex-row items-center justify-center gap-2">
      <span
        class="text-sm font-normal leading-[22px] text-white whitespace-nowrap"
      >
        {{ label }}
      </span>
    </div>
  </button>
</template>

<script setup lang="ts">
interface Props {
  label?: string
}

withDefaults(defineProps<Props>(), {
  label: '确定'
})
</script>

<style scoped>
</style>