import fs from 'fs'
import path from 'path'
import { format } from 'prettier'
import vuePlugin from 'prettier-plugin-vue'

/**
 * 把生成的代码写入文件
 */
export async function writeComponent(code, componentName, outDir, options = {}) {
  const { typescript = true, css = 'tailwind', framework = 'react' } = options
  const isVue = framework === 'vue'
  const ext = isVue ? 'vue' : (typescript ? 'tsx' : 'jsx')

  // 清理代码（模型可能包裹了 markdown fence）
  const cleanCode = stripMarkdownFence(code, isVue)

  // 格式化代码
  let formatted = cleanCode
  try {
    const parser = isVue ? 'vue' : 'babel-ts'
    const pluginsOpt = isVue ? [vuePlugin] : []
    formatted = await format(cleanCode, {
      parser,
      plugins: pluginsOpt,
      semi: false,
      singleQuote: true,
      trailingComma: 'es5',
      printWidth: 100
    })
  } catch (e) {
    // prettier 失败不影响写入
  }

  // 确保目录存在
  const absDir = path.isAbsolute(outDir)
    ? outDir
    : path.join(process.cwd(), outDir)
  fs.mkdirSync(absDir, { recursive: true })

  // 文件路径
  const filename = `${componentName}.${ext}`
  const filePath = path.join(absDir, filename)

  // 加上文件头注释
  // Vue SFC 顶层不能放 // 注释，改用 HTML 注释放在 <template> 前面
  // React 用 // 注释
  let finalCode
  if (isVue) {
    const htmlComment = `<!-- Auto-generated by f2c (figma-to-code) | https://github.com/f2c-cli -->\n`
    finalCode = htmlComment + formatted
  } else {
    const header = `// Auto-generated by f2c (figma-to-code)\n// https://github.com/f2c-cli\n\n`
    finalCode = header + formatted
  }

  // 写入
  fs.writeFileSync(filePath, finalCode, 'utf-8')

  // 如果是 CSS Modules，同时写 .module.css
  if (css === 'cssmodules') {
    const cssContent = extractCssModule(code)
    if (cssContent) {
      const cssPath = path.join(absDir, `${componentName}.module.css`)
      fs.writeFileSync(cssPath, cssContent, 'utf-8')
      return { filePath, cssPath }
    }
  }

  return { filePath }
}

/**
 * 把组件名标准化为 PascalCase
 * "button / primary" -> "ButtonPrimary"
 * "Card Component"   -> "CardComponent"
 */
export function toComponentName(name) {
  return name
    .replace(/[^a-zA-Z0-9\s]/g, ' ')
    .split(/[\s_-]+/)
    .filter(Boolean)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join('')
    || 'Component'
}

// ── 工具函数 ──

function stripMarkdownFence(code, isVue = false) {
  // 去掉 ```vue ... ``` 或 ```tsx ... ``` 等包裹
  return code
    .replace(/^```(?:vue|tsx?|jsx?|javascript|typescript)?\n?/m, '')
    .replace(/\n?```\s*$/m, '')
    .trim()
}

function extractCssModule(code) {
  // 提取模型输出中的 CSS 块（如果有）
  const match = code.match(/```css\n([\s\S]+?)```/)
  return match ? match[1].trim() : null
}
